//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.XMLServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XMLServices.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/transformation", ReplyAction="http://tempuri.org/IService1/transformationResponse")]
        byte[] transformation(string XmlURl, string XslURl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/transformation", ReplyAction="http://tempuri.org/IService1/transformationResponse")]
        System.Threading.Tasks.Task<byte[]> transformationAsync(string XmlURl, string XslURl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XPathSearch", ReplyAction="http://tempuri.org/IService1/XPathSearchResponse")]
        string[] XPathSearch(string URL, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XPathSearch", ReplyAction="http://tempuri.org/IService1/XPathSearchResponse")]
        System.Threading.Tasks.Task<string[]> XPathSearchAsync(string URL, string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.XMLServices.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.XMLServices.IService1>, WebApplication1.XMLServices.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] transformation(string XmlURl, string XslURl) {
            return base.Channel.transformation(XmlURl, XslURl);
        }
        
        public System.Threading.Tasks.Task<byte[]> transformationAsync(string XmlURl, string XslURl) {
            return base.Channel.transformationAsync(XmlURl, XslURl);
        }
        
        public string[] XPathSearch(string URL, string path) {
            return base.Channel.XPathSearch(URL, path);
        }
        
        public System.Threading.Tasks.Task<string[]> XPathSearchAsync(string URL, string path) {
            return base.Channel.XPathSearchAsync(URL, path);
        }
    }
}
